#!/bin/bash

sudo mount --mkdir /dev/disk/by-id/usb-Seagate_BUP_Portable_00000000NABATCW8-0:0-part2 "/run/media/bolleyboll/Aman_HDD"

sudo chgrp plex "/run/media/bolleyboll"
sudo chmod g+rX "/run/media/bolleyboll"
sudo chgrp plex "/run/media/bolleyboll/Aman_HDD"
sudo chmod g+rX "/run/media/bolleyboll/Aman_HDD"
sudo chgrp plex "/run/media/bolleyboll/Aman_HDD/Entertainment"
sudo chmod g+rX "/run/media/bolleyboll/Aman_HDD/Entertainment"

sudo setfacl -R -m g:plex:rx "/run/media/bolleyboll/Aman_HDD/Entertainment"

sudo systemctl start plexmediaserver.service
